apiVersion: apps/v1
kind: Deployment
metadata:
  name: mmff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mmff
  template:
    metadata:
      labels:
        app: mmff
    spec:
      containers:
      - image: okteto.dev/mmff:latest
        name: mmff
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "bf41a6aa-ade5-435b-bc2f-35d02aec39b4"
        - name: Vless_Path
          value: "bf41a6aa-ade5-435b-bc2f-35d02aec39b4-vless"
        - name: Vmess_UUID
          value: "bf41a6aa-ade5-435b-bc2f-35d02aec39b4"
        - name: Vmess_Path
          value: "bf41a6aa-ade5-435b-bc2f-35d02aec39b4-vmess"
        - name: Share_Path
          value: "/v2link"
